apiVersion: v1
kind: Service
metadata:
  name: service
  namespace: veena-ns-lb
spec:
  type: LoadBalancer
  selector:
    app: veena-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 31568